#!/usr/bin/env sh

set -e

# Função para irmos informando o usuário via terminal (CLI) aquilo que estamos a fazer
function info() {
	if [[ -t 1 ]]; then
		printf "%b==>%b %b%s%b\n" "\x1b[1m\x1b[32m" "\x1b[0m" \
		                          "\x1b[1m\x1b[37m" "$1" "\x1b[0m"
	else
		printf "*** %s\n" "$1"
	fi
}
# Função para irmos avisando o usuário via terminal (CLI) aquilo que estamos a fazer
function aviso() {
	if [[ -t 1 ]]; then
		printf "%b==>%b %b%s%b\n" "\x1b[1m\x1b[33m" "\x1b[0m" \
			                  "\x1b[1m\x1b[37m" "$1" "\x1b[0m" >&2
	else
		printf "*** %s\n" "$1" >&2
	fi
}

# A famosa função "Oups"para irmos falando ao usuário quando as coisas poderem dar errado
function oups() {
	set -e
	if [[ -t 1 ]]; then
		printf "%b==>%b %b%s%b\n" "\x1b[1m\x1b[31m" "\x1b[0m" \
		                          "\x1b[1m\x1b[37m" "$1" "\x1b[0m" >&2
	else
		printf "!!! %s\n" "$1" >&2
	fi
}

info "Obrigado por testar o NEORICALEX!"
aviso "Compilando o neoricalex..."
autoreconf --install
./configure
make

aviso "Executando o src/neoricalex..."
src/neoricalex

GH_TOKEN="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"
if [ ! -d ".git" ]; then
	git init
	git add .
	git commit -m "Primeiro Commit"
	git branch -M main
	git remote add origin https://$GH_TOKEN@github.com/neoricalex/dev.git
	git push -u origin main
fi
#rm -rf .git
#git remote set-url origin https://$GH_TOKEN@github.com/neoricalex/dev.git