#!/bin/bash

echo "Actualizar os repositorios e instalar alguns pacotes essenciais..."
sudo apt update && sudo apt upgrade -y
sudo apt install -y curl wget unzip

echo "Checkando se o Docker está instalado..."
if ! command -v docker &> /dev/null;
then
    # Add Docker's official GPG key:
    sudo apt-get update
    sudo apt-get install ca-certificates curl gnupg
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

    # Add the repository to Apt sources:
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update

    # Instala a ultima versao
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
fi

cd docker
if [ ! -f imagem/vps-qemu-v0.0.1/vps-v0.0.1.qcow2 ]; then
    #sudo rm -rf ./imagem
    #sudo rm -rf ./packer_cache
    #sudo docker rmi neoricalex/vps:latest --force

    echo "Checkando se a CLI do GitHub está instalada..."
    if ! command -v gh &> /dev/null;
    then
    type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
        #gh auth login
        #gh auth setup-git
        #git config --global user.name "neoricalex"
        #git config --global user.email "neo.webmaster.2@gmail.com"
        #ssh-keygen -t rsa -b 4096
        #ssh-keygen -t dsa 
        #ssh-keygen -t ecdsa -b 521
        #ssh-keygen -t ed25519
    fi

    sudo docker compose up
    #sudo docker compose up --build --force-recreate

    echo "Checkando se o KVM está instalado..."
    if ! command -v kvm &> /dev/null;
    then
        sudo apt install -y qemu qemu-kvm qemu-efi qemu-system qemu-utils qemu-block-extra \
                        libvirt-daemon libvirt-clients bridge-utils virt-manager qemu-system \
                        qemu-utils qemu-block-extra libvirt-daemon-system cpu-checker \
                        libguestfs-tools libosinfo-bin dnsmasq-base ebtables libvirt-dev

        echo "==> Ligar o Libvirt"
        sudo systemctl enable --now libvirtd

        sudo gpasswd -a $USER libvirt
        sudo gpasswd -a $USER libvirt-qemu # Falta testar
    fi

    virt-install --name vps --memory 2048 --vcpus 1 --disk imagem/vps-qemu-v0.0.1/vps-v0.0.1.qcow2,bus=sata --import --os-variant ubuntu20.04 --network default
fi